unbind C-b
set-option -g prefix C-f
set -g base-index 1              # Window numbers start at 1
setw -g mode-keys vi             # Vi bindings in copy mode
set -s escape-time 0             # No delay after Esc
set -g detach-on-destroy off     # Stay in tmux when session closes
set -g renumber-windows on       # No gaps after closing windows
set -g mouse off                 # Mouse-mode interferes with native terminal selection
set -g default-terminal "tmux-256color"
set-option -sa terminal-overrides ',xterm-256color:RGB'
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'
bind s split-window -v -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"
bind < resize-pane -L 10
bind > resize-pane -R 10
bind + resize-pane -D 10
bind - resize-pane -U 10
bind-key -n C-S-Left swap-window -d -t -1
bind-key -n C-S-Right swap-window -d -t +1

set-window-option -g window-style 'bg=#101010'
set-window-option -g window-active-style 'bg=#151515'

set -g pane-border-style fg=colour238,bg=#101010
set -g pane-active-border-style fg=colour113,bg=#151515

set -g status-bg colour233
set -g status-fg white
set -g status-left '#[fg=green]#S '
set -g status-right '#[fg=green]%d.%m. %H:%M'
set-window-option -g window-status-current-style fg=black,bg=green

